#!/bin/bash

PATH="$(pwd)/bin:$PATH"  # allow dom to be executed without leading "./"
export Etc=$(pwd)/etc
export Test=$(pwd)/test
export Bin=$(pwd)/bin
export Src=$(pwd)/original
export Lua=$(which lua)
export PLATFORM="LINUX"

if [ "$1" = "--run-on-mac" ]
then
	export PLATFORM="OSX"
fi

# did it this way to avoid modifying original Makefile as I am unsure if that is permitted

# make eg0
# make eg0a
# make eg0b
make eg1
